require "modules.options"
require "modules.plugins"
require "modules.theme"
require "modules.develop"
require "modules.global"
-- require "modules.poetry"
require "modules.vimspector"
require "modules.vimvisual"
require "modules.keymaps"
require "modules.floaterm"
-- require("myplugin").setup()
